name: conda_recipes_env
channels:
  - conda-forge
  - shoemakerdr
  - https://conda.anaconda.org/conda-forge
  - defaults
dependencies:
  - anaconda-client
  - black
  - colorama >=0.4, <0.5
  - conda-build
  - conda-verify
  - halo
  - invoke >=1.4, <2.0
